electron-userland/electron-installer-redhat

- README.md
- resources/desktop.ejs
- src/installer.js
- test/installer.js
- adds support for MimeType entry in .desktop file
- shamelessly copies what was done in  electron-installer-debian change (see https://github.com/unindented/electron-installer-debian/commit/70586c5dfeb25437839531c9141bf7b8c9b926de) as files that can be identical seem to be between these repos
> Fixes #27: .desktop file supports configurable MimeType entry

- README.md
The Red Hat/RPM world expect packages to be called “x86_64.rpm”.
Fixing the examples in README.md to match the other test cases and examples.
> Change all examples to x86_64

- README.md
Matches the default format specified in `src/installer.js`.
_(Some background: we're using this package as part of [Electron Forge](https://github.com/electron-userland/electron-forge), and I was going off of the docs to figure out what the output filename is, so we can easily publish it [e.g., to GitHub Releases].)_
> Fix the example RPM filenames in the README

- resources/spec.ejs
Ensures the newly installed icon appears in menus. Otherwise the new program
may not appear until after logging out and back in again.
Supported by GNOME, KDE, others.
This command makes app menus aware of the the newly installed .desktop file.
> Run update-desktop-database after [un]install

- README.md
- src/installer.js
Installing the RPM on a clean copy of the latest Fedora gives the following error:
```
/usr/share/atom/atom: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```
I found a [related issue that hit Atom itself](https://github.com/atom/atom/issues/13176). The resolution was to install libXScrnSaver. Rather than require all users to do this I added it as a default dependency. This is the same solution Atom implemented.
I did verify with libXScrnSaver now included as a requirement I can now install the package and run it without error.
> Include libXScrnSaver as a default dependency

- resources/spec.ejs
- src/installer.js
This was already addressed on the debian side with https://github.com/unindented/electron-installer-debian/pull/47 and for some reason, the change didn't happen on the redhat installer
> Install binary files to /usr/lib/ instead of /usr/share/

- .travis.yml
- README.md
- package-lock.json
- package.json
- src/installer.js
- src/spawn.js
- src/util.js
- test/util.js
Also, require Node 6.
Similar to https://github.com/electron-userland/electron-installer-debian/pull/162
Incidentally, the PR #91 was what prompted me to finally finish the first iteration of the module plus these PRs, since I've already done a chunk of the custom desktop template work (by virtue of copying it from `-debian`).
> Move common functionality to electron-installer-common

- package.json
- src/dependencies.js
- src/installer.js
- test/installer.js
Reference: https://fedoraproject.org/wiki/Packaging:Naming#Common_Character_Set_for_Package_Naming
Addresses electron-userland/electron-forge#654.
Also, cleans up `-common` imports.
> Sanitize package names to conform to Fedora policy

- NEWS.md
- package.json
Also upgrades `electron-installer-common` to `^0.6.1` to pick up the `asar` version bump.
@fcastilloec I am expediting this release due to the security vulnerability in `asar`.
> Release 1.0.1

- src/installer.js
- test/cli.js
It seems that the release number is not optional for RPM. As seen in https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/
> The package release number MUST always be present while the others may or may not be depending on the situation.
This is probably a breaking change too.
This also fixes #113
> Revision fix

- .travis.yml
- README.md
- package.json
- src/dependencies.js
- src/installer.js
- test/dependencies.js
- test/helpers/describe_installer.js
- test/installer.js
BREAKING CHANGE: drop support for Node < 8.
Requires https://github.com/electron-userland/electron-installer-common/pull/27 to be merged/deployed.
> feat: use Node 8 syntax

- README.md
- example/package.json
* remove reference to `electron-prebuilt`
* [Linux/ia32 is no longer offically supported](https://electronjs.org/blog/linux-32bit-support)
* Update Electron dependency
* Better package name
* Clearer script names
> chore: clean up docs & example

- package.json
- src/dependencies.js
> fix: add openSUSE package name variant for kde-cli-tools

- .travis.yml
- src/dependencies.js
This pull request addresses #130. There is a pre-condition that changes in electron-installer-common (see [this pull request](https://github.com/electron-userland/electron-installer-common/pull/40)) are first merged and released on npmjs, before this change can work.
> Add dependency alternatives for OpenSuse Leap 15.1

- NEWS.md
- package.json
* Electron 8 dependency compatibility (electron-userland/electron-installer-common#45)
* Node &lt; 10 support (#151)
> Release 3.0.0

- package.json
- src/dependencies.js
- test/dependencies.js
"npm run make" crashes when the rpmbuild version is `[ 'RPM-Version', '4.15.1' ]`. With this fix, we always take the last part of the version string, which should be the version number.
On my system, the output of `rpmbuild --version` only contains a single string: `RPM-Version 4.15.1`. In this case, making the project crashes with the error message `Cannot read property 'split' of undefined`.
This change always takes the last part of the version string to compare the version number instead of using the hard-coded value `2` as an index - which might not exist.
I am running on:
```
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
```
Fixes #163.
> fix: handle parsing versions from RPM >= 4.15

- package.json
I keep forgetting to run ESLint before making commits. This makes it automatic.
> chore: fix any fixable lint warnings before committing changes

- src/cli.js
It allows you to pass array options via CLI arguments.
> fix: Define array options to yargs

- README.md
- resources/spec.ejs
- test/installer.js
The latest version of `-common` introduced support for symbolic icons but this module needs additional configuration in order for it to work.
`-debian` doesn't require any additional configuration because icons are just copied and there's no need for a specs file.
> feat: add symbolic icon support

- resources/desktop.ejs
- resources/spec.ejs
For both `.ejs` files, I've removed all unnecessary `if` statements, based on options that do have a default so they won't be `undefined`.
For `spec.ejs`, I'm trying to follow [this guide](https://fedoraproject.org/wiki/PeterGordon/SpecFormattingGuidelines) and some other conventions.
One of the requirements, keeping two lines between sections, it's impossible to follow when using lodash. We would have to switch to [`ejs`](https://www.npmjs.com/package/ejs) in order to fine control the spacing between sections.
> fix: make .ejs more readable

- NEWS.md
- package.json
If approved, I'll push the tag so we can release a new version. Hopefully, the CI won't have a problem publishing to npm.
Here's the text that could go into the Releases page:
* Support for scalable and symbolic icons (#169)
* Conformance to [RPM spec formatting guidelines](https://fedoraproject.org/wiki/PeterGordon/SpecFormattingGuidelines) (#171)
> chore: release 3.2.0

- src/dependencies.js
On OpenSuse Leap 15.2 (which is the most recent version), [mesa-libgbm](https://software.opensuse.org/package/mesa-libgbm?search_term=mesa-libgbm) and [libxcb](https://software.opensuse.org/package/libxcb) are not valid package names (when you follow the links you see that the repo page says "There is no official package available for ALL Distributions"). Instead you do find [libgbm1](https://software.opensuse.org/package/libgbm1) and [libxcb1](https://software.opensuse.org/package/libxcb1) as valid packages.
This pull request is to make the adjustment in [src/dependencies.js](https://github.com/electron-userland/electron-installer-redhat/blob/060071451a5859a01eaf0724a685aed21bf0762f/src/dependencies.js) by adding the above mentioned package names libgbm1 and libxcb1 as alternatives to …
> Allow for two different variants of libgbm and libxcb to better support OpenSuse Leap 15.2

- README.md
- src/installer.js
- test/installer.js
This PR adds the option to define the `%_target_os` that it is used in the `target` option of rpmbuild.
> --target PLATFORM
When building the package, interpret PLATFORM as arch-vendor-os and set the macros %_target, %_target_cpu, and %_target_os accordingly.
This PR is related to https://github.com/webtorrent/webtorrent-desktop/issues/1849 as the maintainer uses osx (darwin) to generate linux packages.
> feat: add option to set %_target_os

- README.md
- src/installer.js
- test/installer.js
In #175, we didn't add enough information to the README for the new `options.os` option. This PR fixes that.
@malept let me know if this is enough, I can make any changes you'd like
> refactor: rename options.os to options.platform

- resources/spec.ejs
By default the host's `/usr/bin/strip` is used, which won't work when executables being stripped are for a different architecture.
> fix: skip stripping when making RPM for different architecture

- .github/workflows/ci.yml
* Kills the macOS jobs for now since `brew install rpm` only supports Ventura and there's no older versions available to install
* Updates permissions for the workflow
* Updates actions and pins SHAs
* Expands test coverage to Node.js 16.x and 18.x
> build: update workflow
